### ISSUE TITLE
Where I place "FlowRouterAutoscroll"?

### ISSUE THREAD

**Issue by thearabbit** [tomwasd/flow-router-autoscroll#1]
Where I place "FlowRouterAutoscroll"?
Please example.

**Comment by tomwasd** [comment]
Hi,

You only need to use the FlowRouterAutoscroll variable if you want to change the default animation duration.

If you do, you put it somewhere on the client, outside of any template specific code.

`FlowRouterAutoscroll.animationDuration = 100;`

If you're happy with the default animation duration then you just add the package and it should work! :)

**Comment by thearabbit** [comment]
Thanks for your reply, So if I want to change default I should place it in `Meteor.startup()` in client.

**Comment by danielparas** [comment]
Hi, thanks for this package @tomwasd .. I keep getting "ReferenceError: FlowRouterAutoscroll is not defined" when trying to adjust the animation duration (want to remove it completely) - seems like the variable is not accessable from a Global scope.

**Comment by tomwasd** [comment]
Hi @danielparas,

You're quite right - looks like I forgot to export the FlowRouterAutoscroll variable to the client. I've pushed a new version to github and atmosphere that should fix the issue - just shout if you still have problems :)

**Comment by danielparas** [comment]
Thanks Tom! Works perfect now :)
